version: 2
services:
  - type: web
    name: panda-ai
    env: node
    buildCommand: npm install && npm --workspace server run build && npm --workspace web run build
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
